osx_image: xcode11
sudo: required
dist: xenial
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - app/node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install git-lfs; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils bsdtar ruby-dev build-essential; sudo gem install fpm; fi
before_script:
- git-lfs pull
install:
- nvm install 8
- npm install electron-builder@next
- npm install
- npm prune
script:
- npm run dist
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
